# LandingAI ADE schema configuration for financial document extraction

schemas:
  earnings_10q:
    name: "Earnings 10-Q Extraction"
    document_type: "earnings"
    target_tables:
      - name: "income_statement"
        fields:
          - name: "revenue"
            type: "currency"
            unit: "millions"
            aliases: ["total_revenue", "net_sales", "total_net_sales"]
            validation:
              min_confidence: 0.85
              range: [0, 1000000]
          
          - name: "gross_profit"
            type: "currency"
            unit: "millions"
            aliases: ["gross_income"]
            validation:
              min_confidence: 0.80
              
          - name: "operating_income"
            type: "currency"
            unit: "millions"
            aliases: ["operating_profit", "income_from_operations"]
            
          - name: "net_income"
            type: "currency"
            unit: "millions"
            aliases: ["net_earnings"]
            
          - name: "eps_basic"
            type: "decimal"
            unit: "dollars"
            aliases: ["earnings_per_share_basic", "basic_eps"]
            validation:
              min_confidence: 0.90
              range: [-10, 50]
              
          - name: "eps_diluted"
            type: "decimal"
            unit: "dollars"
            aliases: ["earnings_per_share_diluted", "diluted_eps"]
            validation:
              min_confidence: 0.90
              
      - name: "balance_sheet"
        fields:
          - name: "total_assets"
            type: "currency"
            unit: "millions"
            
          - name: "total_liabilities"
            type: "currency"
            unit: "millions"
            
          - name: "shareholders_equity"
            type: "currency"
            unit: "millions"
            aliases: ["stockholders_equity", "total_equity"]

  compliance_margins:
    name: "Compliance Margin Requirements"
    document_type: "compliance"
    target_tables:
      - name: "margin_requirements"
        fields:
          - name: "scope_class"
            type: "string"
            aliases: ["asset_class", "security_class"]
            
          - name: "initial_margin"
            type: "percentage"
            validation:
              min_confidence: 0.90
              range: [0, 1]
              
          - name: "maintenance_margin"
            type: "percentage"
            validation:
              min_confidence: 0.90
              range: [0, 1]
              
          - name: "effective_date"
            type: "date"
            format: "YYYY-MM-DD"
            aliases: ["implementation_date", "start_date"]
            
      - name: "scope_definition"
        fields:
          - name: "tickers"
            type: "list"
            item_type: "string"
            aliases: ["symbols", "securities"]

extraction_rules:
  confidence_thresholds:
    high: 0.90
    medium: 0.80
    low: 0.70
    
  validation_rules:
    - name: "currency_format"
      pattern: "^\\$?[0-9,]+\\.?[0-9]*[MBK]?$"
      
    - name: "percentage_format"
      pattern: "^[0-9]+\\.?[0-9]*%?$"
      
    - name: "date_format"
      pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$|^[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}$"
      
  post_processing:
    - name: "normalize_currency"
      function: "convert_to_millions"
      
    - name: "normalize_percentage"
      function: "convert_to_decimal"
      
    - name: "standardize_dates"
      function: "iso_format"

quality_checks:
  - name: "completeness"
    threshold: 0.80
    description: "At least 80% of expected fields extracted"
    
  - name: "consistency"
    threshold: 0.90
    description: "Cross-field validation (e.g., revenue > net_income)"
    
  - name: "confidence"
    threshold: 0.85
    description: "Average confidence across all fields"

output_format:
  provenance:
    include_page_number: true
    include_table_coordinates: true
    include_confidence_scores: true
    include_extraction_timestamp: true
    
  normalization:
    currency_unit: "millions"
    percentage_format: "decimal"
    date_format: "iso"
